# Generated by Django 5.0.14 on 2025-12-05 07:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_local', models.CharField(max_length=255)),
                ('category_id', models.IntegerField()),
                ('description_local', models.TextField()),
                ('material_composition', models.TextField(blank=True)),
                ('production_technique', models.CharField(blank=True, max_length=50)),
                ('finishing_type', models.CharField(blank=True, max_length=50)),
                ('quality_specs', models.JSONField(blank=True, default=dict)),
                ('durability_claim', models.CharField(blank=True, max_length=255)),
                ('packaging_type', models.CharField(blank=True, max_length=100)),
                ('dimensions_l_w_h', models.JSONField(blank=True, default=dict)),
                ('weight_net', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('weight_gross', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business_profiles.businessprofile')),
            ],
            options={
                'db_table': 'products_product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hs_code_recommendation', models.CharField(blank=True, max_length=16, null=True)),
                ('sku_generated', models.CharField(blank=True, max_length=64, null=True)),
                ('name_english_b2b', models.CharField(blank=True, max_length=255, null=True)),
                ('description_english_b2b', models.TextField(blank=True, null=True)),
                ('marketing_highlights', models.JSONField(blank=True, default=list)),
                ('last_updated_ai', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrichment', to='products.product')),
            ],
            options={
                'db_table': 'products_productenrichment',
            },
        ),
    ]
