# Generated by Django 5.0.14 on 2025-12-06 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title of the module", max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Description of the module", verbose_name="description"
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(default=0, help_text="Order for display", verbose_name="order index"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "Module",
                "verbose_name_plural": "Modules",
                "db_table": "modules",
                "ordering": ["order_index", "-created_at"],
                "indexes": [models.Index(fields=["order_index"], name="modules_order_i_65cb7c_idx")],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(help_text="Title of the article", max_length=255, verbose_name="title")),
                ("content", models.TextField(help_text="Article content (Markdown supported)", verbose_name="content")),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional video URL (YouTube, Vimeo, etc.)",
                        max_length=500,
                        null=True,
                        verbose_name="video url",
                    ),
                ),
                (
                    "file_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional file URL (PDF, image, etc.)",
                        max_length=500,
                        null=True,
                        verbose_name="file url",
                    ),
                ),
                (
                    "order_index",
                    models.IntegerField(default=0, help_text="Order within the module", verbose_name="order index"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="educational_materials.module",
                        verbose_name="module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "articles",
                "ordering": ["order_index", "-created_at"],
                "indexes": [models.Index(fields=["module", "order_index"], name="articles_module__e6c6ae_idx")],
            },
        ),
    ]
