"""
Kolosal AI Service for ExportReady.AI

Implements AI Services for Product Enrichment:
- HS Code recommendation menggunakan data_HS sebagai context
- SKU generation

# PBI-BE-M2-06: Service: AI HS Code Mapper
# - Input: name_local, material_composition, category
# - Logic: Query dengan LLM untuk suggest HS Code menggunakan data_HS sebagai context
# - Output: hs_code_recommendation (string 8 digit) + status (from_ai: bool)

# PBI-BE-M2-08: Service: AI SKU Generator
# - Input: category, material_composition, product_id, business_id
# - Logic: Extract 3 huruf dari category → CAT, 3 huruf dari material → MAT
# - Format: {CAT}-{MAT}-{SEQ} contoh: BAG-LTH-001
# - Output: sku_generated (string)
"""

import logging
import re
from typing import Dict, Tuple

from django.conf import settings
from openai import OpenAI

# Import HS Code loader
try:
    from apps.products.utils.hs_code_loader import get_hs_loader
except ImportError:
    get_hs_loader = None

logger = logging.getLogger(__name__)


class KolosalAIService:
    """
    Service class for interacting with Kolosal AI API.
    Uses OpenAI-compatible SDK.
    """

    def __init__(self):
        api_key = settings.KOLOSAL_API_KEY
        if not api_key or api_key.strip() == "":
            logger.error("KOLOSAL_API_KEY is not set in environment variables!")
            raise ValueError("KOLOSAL_API_KEY is required. Please set it in your .env file.")
        
        self.client = OpenAI(
            api_key=api_key.strip(),
            base_url=settings.KOLOSAL_BASE_URL,
        )
        self.model = settings.KOLOSAL_MODEL
        self.hs_loader = get_hs_loader() if get_hs_loader else None
        
        # Log initialization
        api_key_preview = f"{api_key[:8]}..." if len(api_key) > 8 else "***"
        logger.info(f"Kolosal AI Service initialized - Model: {self.model}, API Key: {api_key_preview}")

    def _call_ai(self, prompt: str, system_prompt: str = None) -> str:
        """
        Make a call to Kolosal AI API.

        Args:
            prompt: The user prompt
            system_prompt: Optional system prompt for context

        Returns:
            The AI response text
        """
        messages = []

        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})

        messages.append({"role": "user", "content": prompt})

        try:
            logger.debug(f"Calling Kolosal AI API with model: {self.model}")
            response = self.client.chat.completions.create(
                model=self.model,
                messages=messages,
                temperature=0.1,  # Low temperature for consistent results
            )
            result = response.choices[0].message.content.strip()
            logger.debug(f"AI API response received: {result[:100]}...")
            return result
        except Exception as e:
            logger.error(f"Kolosal AI API error: {e}", exc_info=True)
            raise

    def generate_hs_code(
        self,
        product_name: str,
        material_composition: str,
        category: str = "",
        description: str = "",
    ) -> Tuple[str, bool]:
        """
        Generate HS Code menggunakan AI dengan data_HS sebagai context.

        Args:
            product_name: Local product name
            material_composition: Materials used in the product
            category: Product category
            description: Product description

        Returns:
            Tuple of (hs_code: str, from_ai: bool)
            - hs_code: 8-digit HS Code recommendation
            - from_ai: True if generated by AI, False if fallback
        """
        # Get relevant HS codes from database as context
        hs_context = ""
        if self.hs_loader:
            try:
                hs_context = self.hs_loader.get_hs_code_context(
                    product_name=product_name,
                    material_composition=material_composition,
                    category=category,
                    max_codes=15,
                )
            except Exception as e:
                logger.warning(f"Error loading HS codes context: {e}")

        system_prompt = """Kamu adalah ahli klasifikasi HS Code (Harmonized System Code) untuk ekspor Indonesia.

TUGAS: Tentukan HS Code 8 digit yang PALING TEPAT untuk produk.

ATURAN:
1. Jika ada daftar HS codes sebagai referensi, pilih yang paling sesuai
2. Jika tidak ada yang cocok di daftar, tentukan sendiri berdasarkan pengetahuan HS Code
3. Format output: HANYA 8 digit angka (contoh: 46021200)
4. Jika kode hanya 6 digit, tambahkan "00" di belakang (460212 → 46021200)
5. JANGAN berikan penjelasan, teks, atau karakter lain - HANYA 8 digit angka"""

        prompt_parts = [
            "Tentukan HS Code 8 digit untuk produk berikut:",
            "",
            f"Nama Produk: {product_name}",
            f"Material: {material_composition}",
            f"Kategori: {category}",
        ]
        
        if description:
            prompt_parts.append(f"Deskripsi: {description[:200]}")
        
        if hs_context:
            prompt_parts.append("")
            prompt_parts.append(hs_context)
            prompt_parts.append("")
            prompt_parts.append("Pilih HS Code 8 digit yang PALING TEPAT dari daftar di atas, atau tentukan sendiri jika tidak ada yang cocok.")
        else:
            prompt_parts.append("")
            prompt_parts.append("Tentukan HS Code 8 digit yang paling sesuai.")
        
        prompt_parts.append("")
        prompt_parts.append("HS Code 8 digit (hanya angka):")

        prompt = "\n".join(prompt_parts)

        try:
            logger.info(f"Generating HS code using AI for: {product_name}")
            response = self._call_ai(prompt, system_prompt)
            logger.info(f"AI response for HS code: {response}")
            
            # Extract only digits from response
            digits_only = re.sub(r'\D', '', response)
            logger.info(f"Extracted digits: {digits_only} (length: {len(digits_only)})")
            
            # Try to get 8 digits
            if len(digits_only) >= 8:
                hs_code = digits_only[:8]
                if hs_code.isdigit():
                    logger.info(f"✓ HS Code generated by AI: {hs_code}")
                    return hs_code, True
            
            # If we got 6 digits, pad with "00" to make 8 digits
            if len(digits_only) == 6 and digits_only.isdigit():
                hs_code = digits_only + "00"
                logger.info(f"✓ HS Code 6-digit from AI, padded to 8: {hs_code}")
                return hs_code, True
            
            # If we got 4-7 digits, pad to 8
            if 4 <= len(digits_only) < 8 and digits_only.isdigit():
                hs_code = digits_only.ljust(8, '0')
                logger.info(f"✓ HS Code padded from {len(digits_only)} to 8: {hs_code}")
                return hs_code, True

            # Fallback: try to find from HS loader if available
            if self.hs_loader:
                try:
                    logger.warning("AI response invalid, trying HS loader fallback...")
                    codes = self.hs_loader.search_hs_codes(
                        keywords=f"{product_name} {material_composition}",
                        max_results=1,
                        min_level=6,
                    )
                    if codes:
                        hscode = codes[0]["hscode"]
                        # Pad to 8 digits
                        if len(hscode) == 6:
                            hscode = hscode + "00"
                        elif len(hscode) < 8:
                            hscode = hscode.ljust(8, '0')
                        logger.info(f"✓ Found HS code from database: {hscode}")
                        return hscode, False
                except Exception as e:
                    logger.warning(f"Error getting HS code from loader: {e}")

            # Final fallback
            logger.error(f"✗ HS Code generation FAILED")
            logger.error(f"  Product: {product_name}")
            logger.error(f"  Raw AI response: '{response}'")
            logger.error(f"  Extracted digits: '{digits_only}'")
            return "00000000", False

        except Exception as e:
            logger.error(f"✗ Error generating HS Code: {e}", exc_info=True)
            return "00000000", False

    def generate_sku(
        self,
        category: str,
        material_composition: str,
        product_id: int,
        business_id: int,
        product_name: str = "",
    ) -> str:
        """
        Generate SKU code.

        Args:
            category: Product category
            material_composition: Primary material
            product_id: Product ID for sequence
            business_id: Business ID for uniqueness
            product_name: Product name (used as fallback if category is numeric)

        Returns:
            Generated SKU code
        """
        # Extract 3 letters from category
        # If category is numeric or empty, use product name instead
        if not category or category.isdigit() or self._extract_code(category, 3) == "XXX":
            if product_name:
                cat_code = self._extract_code(product_name, 3)
            else:
                cat_code = "PRD"
        else:
            cat_code = self._extract_code(category, 3)

        # Extract 3 letters from material
        mat_code = self._extract_code(material_composition, 3)
        if mat_code == "XXX" and product_name:
            # Try to extract from product name if material extraction failed
            mat_code = self._extract_code(product_name, 3)

        # Generate sequence number
        seq = f"{product_id:03d}"

        return f"{cat_code}-{mat_code}-{seq}"

    def _extract_code(self, text: str, length: int = 3) -> str:
        """
        Extract code from text (first N consonants or characters).

        Args:
            text: Input text
            length: Desired code length

        Returns:
            Extracted code in uppercase
        """
        if not text:
            return "XXX"[:length]

        # Remove non-alphabetic characters
        clean = re.sub(r'[^a-zA-Z]', '', text)

        if not clean:
            return "XXX"[:length]

        # Take first N characters
        code = clean[:length].upper()

        # Pad if needed
        while len(code) < length:
            code += "X"

        return code

    def enrich_product(
        self,
        product_name: str,
        description_local: str,
        material_composition: str,
        category: str,
        product_id: int,
        business_id: int,
    ) -> Dict:
        """
        Product enrichment - hanya HS Code dan SKU.

        Args:
            product_name: Local product name
            description_local: Description in Indonesian
            material_composition: Materials used
            category: Product category
            product_id: Product ID
            business_id: Business ID

        Returns:
            Dictionary dengan hs_code_recommendation, sku_generated, dan status
        """
        # Generate HS Code dengan AI
        hs_code, hs_from_ai = self.generate_hs_code(
            product_name, material_composition, category, description_local
        )
        
        # Generate SKU
        sku = self.generate_sku(
            category, material_composition, product_id, business_id, product_name
        )
        
        return {
            "hs_code_recommendation": hs_code,
            "sku_generated": sku,
            "hs_code_from_ai": hs_from_ai,  # Status apakah HS code dari AI atau fallback
        }

    def get_market_intelligence(
        self,
        product_name: str,
        description: str,
        material_composition: str,
        category: str = "",
        current_price_usd: float = None,
        production_capacity: int = None,
    ) -> Dict:
        """
        AI Market Intelligence - Get market analysis and country recommendations.
        
        Uses the same _call_ai method that works for product enrichment.
        
        Returns:
            Dict with market intelligence data
        """
        import json
        import re
        
        # Validate and sanitize inputs
        product_name = str(product_name or "").strip()[:200]
        description = str(description or "").strip()[:500]
        material_composition = str(material_composition or "").strip()[:200]
        category = str(category or "").strip()[:100]
        
        system_prompt = """Kamu adalah ahli market intelligence dan perdagangan internasional.
Tugasmu adalah menganalisis produk dan memberikan rekomendasi pasar ekspor yang tepat.

ATURAN:
- Berikan rekomendasi berdasarkan data tren pasar terkini
- Pertimbangkan cultural preferences, regulasi, dan demand
- Sertakan alasan konkret untuk setiap rekomendasi
- Fokus pada pasar yang realistis untuk UMKM Indonesia
- Output HARUS dalam format JSON yang valid"""

        # Build prompt with proper escaping
        price_str = f"${current_price_usd:.2f}" if current_price_usd else "Belum ditentukan"
        capacity_str = f"{production_capacity} unit/bulan" if production_capacity else "N/A"
        
        prompt_parts = [
            "Analisis produk berikut dan berikan market intelligence:",
            "",
            "INFORMASI PRODUK:",
            f"- Nama Produk: {product_name}",
            f"- Deskripsi: {description}",
            f"- Material: {material_composition}",
            f"- Kategori: {category}",
            f"- Harga Saat Ini (USD): {price_str}",
            f"- Kapasitas Produksi: {capacity_str}",
            "",
            "OUTPUT FORMAT (dalam JSON):",
            '{"recommended_countries": [{"country": "Country Name", "country_code": "XX", "score": 85, "reason": "Alasan", "market_size": "Large/Medium/Small", "competition_level": "High/Medium/Low", "suggested_price_range": "$XX - $XX", "entry_strategy": "Strategi"}], "countries_to_avoid": [{"country": "Country Name", "country_code": "XX", "reason": "Alasan"}], "market_trends": ["Trend 1", "Trend 2"], "competitive_landscape": "Analisis", "growth_opportunities": ["Opportunity 1"], "risks_and_challenges": ["Risk 1"], "overall_recommendation": "Rekomendasi"}',
            "",
            "Berikan minimal 3 negara rekomendasi dan 2 negara yang sebaiknya dihindari.",
            "Output dalam format JSON yang valid."
        ]
        
        prompt = "\n".join(prompt_parts)

        try:
            # Use the same _call_ai that works for product enrichment
            response = self._call_ai(prompt, system_prompt)

            # Extract JSON from response
            json_match = re.search(r'\{[\s\S]*\}', response)
            if json_match:
                result = json.loads(json_match.group())
                return {
                    "success": True,
                    "data": result
                }

            return {
                "success": False,
                "error": "Failed to parse market intelligence response",
                "raw_response": response
            }

        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse market intelligence JSON: {e}")
            return {
                "success": False,
                "error": "Failed to parse AI response"
            }
        except Exception as e:
            logger.error(f"Error getting market intelligence: {e}")
            return {
                "success": False,
                "error": str(e)
            }