# Generated by Django 5.0.14 on 2025-12-05 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_code", models.CharField(max_length=2, primary_key=True, serialize=False)),
                ("country_name", models.CharField(max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "db_table": "countries",
                "ordering": ["country_name"],
            },
        ),
        migrations.CreateModel(
            name="CountryRegulation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rule_category",
                    models.CharField(
                        choices=[("Ingredient", "Ingredient"), ("Labeling", "Labeling"), ("Physical", "Physical")],
                        max_length=20,
                    ),
                ),
                (
                    "forbidden_keywords",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated banned keywords, e.g., 'Pewarna K10, Sawit Non-RSPO'",
                    ),
                ),
                (
                    "required_specs",
                    models.TextField(
                        blank=True, default="", help_text="Required specifications, e.g., 'Allergen Info, Presisi 1mm'"
                    ),
                ),
                ("description_rule", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulations",
                        to="export_analysis.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country Regulation",
                "verbose_name_plural": "Country Regulations",
                "db_table": "country_regulations",
                "indexes": [models.Index(fields=["country", "rule_category"], name="country_reg_country_5e80a1_idx")],
            },
        ),
        migrations.CreateModel(
            name="ExportAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("readiness_score", models.IntegerField(default=0, help_text="Score 0-100")),
                (
                    "status_grade",
                    models.CharField(
                        choices=[("Ready", "Ready"), ("Warning", "Warning"), ("Critical", "Critical")],
                        default="Warning",
                        max_length=10,
                    ),
                ),
                (
                    "compliance_issues",
                    models.JSONField(default=list, help_text="Detail temuan AI (Missing Spec, Banned Item)"),
                ),
                ("recommendations", models.TextField(blank=True, default="")),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_analyses",
                        to="products.product",
                    ),
                ),
                (
                    "target_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_analyses",
                        to="export_analysis.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export Analysis",
                "verbose_name_plural": "Export Analyses",
                "db_table": "export_analyses",
                "indexes": [
                    models.Index(fields=["product"], name="export_anal_product_bea548_idx"),
                    models.Index(fields=["target_country"], name="export_anal_target__f9c053_idx"),
                    models.Index(fields=["readiness_score"], name="export_anal_readine_53011e_idx"),
                ],
                "unique_together": {("product", "target_country")},
            },
        ),
    ]
