# Generated by Django 5.0.14 on 2025-12-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("export_analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportanalysis",
            name="product_snapshot",
            field=models.JSONField(
                default=dict,
                help_text="Snapshot of product data at analysis time (includes product and enrichment data)",
            ),
        ),
        migrations.AddField(
            model_name="exportanalysis",
            name="regulation_recommendations_cache",
            field=models.JSONField(blank=True, default=dict, help_text="Cached detailed regulation recommendations"),
        ),
    ]
