# Generated by Django 5.0.14 on 2025-12-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('export_analysis', '0002_add_product_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportanalysis',
            name='regulation_snapshot',
            field=models.JSONField(default=dict, help_text='Snapshot of regulations checked at analysis time'),
        ),
    ]
