# Generated by Django 5.0.14 on 2025-12-06 17:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForwarderProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=255, verbose_name="company name")),
                (
                    "contact_info",
                    models.JSONField(
                        default=dict,
                        help_text="Contact information (phone, email, address, etc.)",
                        verbose_name="contact info",
                    ),
                ),
                (
                    "specialization_routes",
                    models.JSONField(
                        default=list,
                        help_text="Array of route codes (e.g., ['ID-JP', 'ID-US'])",
                        verbose_name="specialization routes",
                    ),
                ),
                (
                    "service_types",
                    models.JSONField(
                        default=list,
                        help_text="Array of service types (e.g., ['Sea Freight', 'Air Freight'])",
                        verbose_name="service types",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=0,
                        help_text="Average rating (1.0-5.0)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="average rating",
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0, verbose_name="total reviews")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "Forwarder"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forwarder_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forwarder Profile",
                "verbose_name_plural": "Forwarder Profiles",
                "db_table": "forwarder_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForwarderReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Rating from 1 to 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="rating",
                    ),
                ),
                ("review_text", models.TextField(blank=True, default="", verbose_name="review text")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "forwarder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="forwarders.forwarderprofile",
                        verbose_name="forwarder",
                    ),
                ),
                (
                    "umkm",
                    models.ForeignKey(
                        limit_choices_to={"role": "UMKM"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forwarder_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="UMKM",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forwarder Review",
                "verbose_name_plural": "Forwarder Reviews",
                "db_table": "forwarder_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="forwarderprofile",
            index=models.Index(fields=["average_rating"], name="forwarder_p_average_fedafa_idx"),
        ),
        migrations.AddIndex(
            model_name="forwarderreview",
            index=models.Index(fields=["forwarder"], name="forwarder_r_forward_1abd34_idx"),
        ),
        migrations.AddIndex(
            model_name="forwarderreview",
            index=models.Index(fields=["umkm"], name="forwarder_r_umkm_id_49318b_idx"),
        ),
        migrations.AddIndex(
            model_name="forwarderreview",
            index=models.Index(fields=["rating"], name="forwarder_r_rating_2e5f13_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="forwarderreview",
            unique_together={("forwarder", "umkm")},
        ),
    ]
