# Generated by Django 5.0.14 on 2025-12-06 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCatalog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "is_published",
                    models.BooleanField(default=False, help_text="Whether this catalog is visible to buyers"),
                ),
                ("display_name", models.CharField(help_text="Commercial name displayed to buyers", max_length=255)),
                (
                    "marketing_description",
                    models.TextField(blank=True, help_text="Marketing description (commercial, not technical)"),
                ),
                (
                    "min_order_quantity",
                    models.DecimalField(decimal_places=2, default=1, help_text="Minimum order quantity", max_digits=10),
                ),
                (
                    "unit_type",
                    models.CharField(
                        choices=[
                            ("pcs", "Pieces"),
                            ("pack", "Pack"),
                            ("kg", "Kilogram"),
                            ("set", "Set"),
                            ("box", "Box"),
                            ("carton", "Carton"),
                            ("dozen", "Dozen"),
                        ],
                        default="pcs",
                        help_text="Unit type for ordering",
                        max_length=20,
                    ),
                ),
                ("base_price_exw", models.DecimalField(decimal_places=2, help_text="EXW price in USD", max_digits=12)),
                (
                    "base_price_fob",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="FOB price in USD (optional)", max_digits=12, null=True
                    ),
                ),
                (
                    "base_price_cif",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="CIF price in USD (optional)", max_digits=12, null=True
                    ),
                ),
                ("lead_time_days", models.PositiveIntegerField(default=14, help_text="Production lead time in days")),
                (
                    "available_stock",
                    models.PositiveIntegerField(default=0, help_text="Available stock for immediate order"),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags for search/filter (e.g., ['eco-friendly', 'handmade'])",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, help_text="When the catalog was first published", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Product this catalog entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="catalog",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Catalog",
                "verbose_name_plural": "Product Catalogs",
                "db_table": "product_catalogs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CatalogVariant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "variant_name",
                    models.CharField(help_text="Variant name (e.g., 'Large', 'Spicy', 'Red')", max_length=100),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, help_text="Variant attributes (e.g., {'color': 'red', 'size': 'L'})"
                    ),
                ),
                (
                    "variant_price",
                    models.DecimalField(decimal_places=2, help_text="Price for this variant in USD", max_digits=12),
                ),
                (
                    "moq_variant",
                    models.DecimalField(
                        decimal_places=2, default=1, help_text="Minimum order quantity for this variant", max_digits=10
                    ),
                ),
                ("sku", models.CharField(blank=True, help_text="SKU for this variant", max_length=50)),
                ("is_available", models.BooleanField(default=True, help_text="Whether this variant is available")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        help_text="Catalog this variant belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalogs.productcatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Variant",
                "verbose_name_plural": "Catalog Variants",
                "db_table": "catalog_variants",
                "ordering": ["variant_name"],
            },
        ),
        migrations.CreateModel(
            name="ProductCatalogImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image_url", models.URLField(help_text="URL to the image", max_length=500)),
                ("alt_text", models.CharField(blank=True, help_text="Alt text for accessibility", max_length=255)),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Display order (lower = first)")),
                ("is_primary", models.BooleanField(default=False, help_text="Primary image for thumbnail")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        help_text="Catalog this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalogs.productcatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Image",
                "verbose_name_plural": "Catalog Images",
                "db_table": "product_catalog_images",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
