# Generated by Django 5.0.14 on 2025-12-07 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0002_productcatalog_export_description_and_more"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogpricingresult",
            name="catalog",
        ),
        migrations.CreateModel(
            name="ProductMarketIntelligence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "recommended_countries",
                    models.JSONField(default=list, help_text="List of recommended target countries with details"),
                ),
                (
                    "countries_to_avoid",
                    models.JSONField(default=list, help_text="List of countries to avoid with reasons"),
                ),
                ("market_trends", models.JSONField(default=list, help_text="List of relevant market trends")),
                ("competitive_landscape", models.TextField(blank=True, help_text="Competitive landscape analysis")),
                ("growth_opportunities", models.JSONField(default=list, help_text="List of growth opportunities")),
                ("risks_and_challenges", models.JSONField(default=list, help_text="List of risks and challenges")),
                ("overall_recommendation", models.TextField(blank=True, help_text="Overall strategic recommendation")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Product this market intelligence belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_intelligence",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Market Intelligence",
                "verbose_name_plural": "Product Market Intelligence",
                "db_table": "product_market_intelligence",
            },
        ),
        migrations.CreateModel(
            name="ProductPricingResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cogs_per_unit_idr",
                    models.DecimalField(
                        decimal_places=2, help_text="Cost of goods sold per unit in IDR", max_digits=12
                    ),
                ),
                (
                    "target_margin_percent",
                    models.DecimalField(decimal_places=2, help_text="Target margin percentage", max_digits=5),
                ),
                (
                    "target_country_code",
                    models.CharField(
                        blank=True, help_text="Target country for CIF calculation", max_length=2, null=True
                    ),
                ),
                (
                    "exchange_rate_used",
                    models.DecimalField(
                        decimal_places=2, help_text="Exchange rate used for calculation", max_digits=12
                    ),
                ),
                ("exw_price_usd", models.DecimalField(decimal_places=2, help_text="EXW price in USD", max_digits=12)),
                ("fob_price_usd", models.DecimalField(decimal_places=2, help_text="FOB price in USD", max_digits=12)),
                (
                    "cif_price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="CIF price in USD (if target country provided)",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "pricing_insight",
                    models.TextField(blank=True, help_text="AI-generated pricing insight and recommendations"),
                ),
                ("pricing_breakdown", models.JSONField(default=dict, help_text="Detailed pricing breakdown")),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        help_text="Product this pricing result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_result",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Pricing Result",
                "verbose_name_plural": "Product Pricing Results",
                "db_table": "product_pricing_results",
            },
        ),
        migrations.DeleteModel(
            name="CatalogMarketIntelligence",
        ),
        migrations.DeleteModel(
            name="CatalogPricingResult",
        ),
    ]
