# Generated by Django 5.0.14 on 2025-12-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0002_catalogmarketintelligence_catalogpricingresult"),
        ("catalogs", "0003_remove_catalogpricingresult_catalog_and_more"),
    ]

    operations = []
