# Generated by Django 5.0.14 on 2025-12-07 04:49

import apps.catalogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0004_merge_20251207_1149"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcatalogimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Uploaded image file",
                null=True,
                upload_to=apps.catalogs.models.catalog_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="productcatalogimage",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="External URL to the image (alternative to upload)", max_length=500
            ),
        ),
    ]
