# Generated by Django 5.0.14 on 2025-12-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogs", "0005_remove_catalogpricingresult_catalog_and_more"),
    ]

    operations = [
        # Note: RemoveField operations removed as tables don't exist in DB
        migrations.CreateModel(
            name="CatalogVariantType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type_code",
                    models.CharField(
                        choices=[
                            ("color", "Warna"),
                            ("size", "Ukuran"),
                            ("material", "Bahan"),
                            ("flavor", "Rasa"),
                            ("weight", "Berat"),
                            ("style", "Gaya"),
                            ("pattern", "Motif"),
                            ("custom", "Lainnya"),
                        ],
                        default="custom",
                        help_text="Predefined variant type code",
                        max_length=50,
                    ),
                ),
                (
                    "type_name",
                    models.CharField(
                        help_text="Display name for this variant type (e.g., 'Warna', 'Ukuran', or custom name)",
                        max_length=100,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Display order")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        help_text="Catalog this variant type belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variant_types",
                        to="catalogs.productcatalog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Variant Type",
                "verbose_name_plural": "Catalog Variant Types",
                "db_table": "catalog_variant_types",
                "ordering": ["sort_order", "id"],
                "unique_together": {("catalog", "type_name")},
            },
        ),
        migrations.CreateModel(
            name="CatalogVariantOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "option_name",
                    models.CharField(help_text="Option name (e.g., 'Merah', 'Biru', 'S', 'M', 'L')", max_length=100),
                ),
                ("sort_order", models.PositiveIntegerField(default=0, help_text="Display order")),
                ("is_available", models.BooleanField(default=True, help_text="Whether this option is available")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant_type",
                    models.ForeignKey(
                        help_text="Variant type this option belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="catalogs.catalogvarianttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catalog Variant Option",
                "verbose_name_plural": "Catalog Variant Options",
                "db_table": "catalog_variant_options",
                "ordering": ["sort_order", "id"],
                "unique_together": {("variant_type", "option_name")},
            },
        ),
        # Note: DeleteModel operations removed as tables don't exist in DB
    ]
