# Generated by Django 5.0.14 on 2025-12-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_merge_20251207_0952'),
        ('catalogs', '0006_remove_catalogpricingresult_catalog_and_more'),
    ]

    operations = [
    ]
