# Generated by Django 5.0.14 on 2025-12-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_merge_20251207_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogpricingresult',
            name='catalog',
        ),
        migrations.RemoveField(
            model_name='catalogvariant',
            name='catalog',
        ),
        migrations.DeleteModel(
            name='CatalogMarketIntelligence',
        ),
        migrations.DeleteModel(
            name='CatalogPricingResult',
        ),
        migrations.DeleteModel(
            name='CatalogVariant',
        ),
    ]
