# Generated by Django 5.0.14 on 2025-12-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HSSection",
            fields=[
                ("section", models.CharField(max_length=5, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "HS Section",
                "verbose_name_plural": "HS Sections",
                "db_table": "master_hs_sections",
                "ordering": ["section"],
            },
        ),
        migrations.CreateModel(
            name="HSCode",
            fields=[
                ("hs_code", models.CharField(max_length=16, primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("description_id", models.TextField(blank=True, default="")),
                ("level", models.IntegerField(default=6)),
                ("hs_chapter", models.CharField(blank=True, default="", max_length=2)),
                ("hs_heading", models.CharField(blank=True, default="", max_length=4)),
                ("hs_subheading", models.CharField(blank=True, default="", max_length=6)),
                ("keywords", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="master_data.hscode",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hs_codes",
                        to="master_data.hssection",
                    ),
                ),
            ],
            options={
                "verbose_name": "HS Code",
                "verbose_name_plural": "HS Codes",
                "db_table": "master_hs_codes",
                "ordering": ["hs_code"],
                "indexes": [
                    models.Index(fields=["hs_chapter"], name="master_hs_c_hs_chap_fbfad5_idx"),
                    models.Index(fields=["hs_heading"], name="master_hs_c_hs_head_c7ec16_idx"),
                    models.Index(fields=["level"], name="master_hs_c_level_6068b8_idx"),
                ],
            },
        ),
    ]
