# Generated by Django 5.0.14 on 2025-12-05 15:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("currency_from", models.CharField(default="IDR", max_length=3)),
                ("currency_to", models.CharField(default="USD", max_length=3)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Exchange rate (e.g., 0.000063 for IDR to USD)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="manual", help_text="Source of rate: 'manual', 'api', etc.", max_length=50
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "costing_exchangerate",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Costing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cogs_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost of Goods Sold per unit (IDR)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "packing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Packing cost per unit (IDR)",
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "target_margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Target profit margin percentage",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "recommended_exw_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="EXW price in USD", max_digits=15, null=True
                    ),
                ),
                (
                    "recommended_fob_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="FOB price in USD", max_digits=15, null=True
                    ),
                ),
                (
                    "recommended_cif_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="CIF price in USD (if target country available)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "trucking_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated trucking cost to port (USD)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "document_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Documentation cost (USD)", max_digits=15, null=True
                    ),
                ),
                (
                    "freight_cost_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Freight cost to destination (USD)",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "insurance_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=2, help_text="Insurance cost (USD)", max_digits=15, null=True
                    ),
                ),
                (
                    "container_20ft_capacity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of units that fit in 20ft container", null=True
                    ),
                ),
                (
                    "container_40ft_capacity",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of units that fit in 40ft container", null=True
                    ),
                ),
                ("optimization_notes", models.TextField(blank=True, help_text="AI suggestions for optimization")),
                (
                    "exchange_rate_used",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="IDR to USD rate used for calculation",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "target_country_code",
                    models.CharField(
                        blank=True, help_text="Target country for CIF calculation", max_length=2, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="costings", to="products.product"
                    ),
                ),
            ],
            options={
                "db_table": "costing_costing",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["product"], name="costing_cos_product_a31a15_idx")],
            },
        ),
    ]
