# Generated by Django 5.0.14 on 2025-12-05 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nilai tukar IDR ke USD (e.g., 15800)",
                        max_digits=10,
                        verbose_name="IDR to USD exchange rate",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Update by Admin"),
                            ("api", "External API"),
                            ("bank", "Bank Source"),
                        ],
                        default="manual",
                        help_text="Sumber data nilai tukar",
                        max_length=100,
                        verbose_name="Rate source",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="Waktu terakhir update rate")),
            ],
            options={
                "verbose_name": "Exchange Rate",
                "verbose_name_plural": "Exchange Rates",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Costing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "cogs_per_unit",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Biaya produksi per unit dalam IDR",
                        max_digits=15,
                        verbose_name="Cost of Goods Sold per unit (IDR)",
                    ),
                ),
                (
                    "packing_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Biaya packing/kemasan ekspor per unit dalam IDR",
                        max_digits=15,
                        verbose_name="Packing cost per unit (IDR)",
                    ),
                ),
                (
                    "target_margin_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="Target margin keuntungan dalam persen",
                        max_digits=5,
                        verbose_name="Target profit margin (%)",
                    ),
                ),
                (
                    "recommended_exw_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Harga Ex-Works yang direkomendasikan (USD)",
                        max_digits=15,
                        null=True,
                        verbose_name="Recommended Ex-Works price (USD)",
                    ),
                ),
                (
                    "recommended_fob_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Harga FOB yang direkomendasikan (USD)",
                        max_digits=15,
                        null=True,
                        verbose_name="Recommended FOB price (USD)",
                    ),
                ),
                (
                    "recommended_cif_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Harga CIF (dengan freight & insurance) dalam USD",
                        max_digits=15,
                        null=True,
                        verbose_name="Recommended CIF price (USD)",
                    ),
                ),
                (
                    "container_20ft_capacity",
                    models.IntegerField(
                        blank=True,
                        help_text="Estimasi jumlah unit yang muat dalam 20ft container",
                        null=True,
                        verbose_name="20ft Container capacity (units)",
                    ),
                ),
                (
                    "optimization_notes",
                    models.TextField(
                        blank=True,
                        help_text="Saran dari AI untuk optimasi container/packaging",
                        verbose_name="Container optimization notes",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Waktu terakhir perhitungan dilakukan",
                        verbose_name="Last calculated timestamp",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product this costing is calculated for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costings",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costing",
                "verbose_name_plural": "Costings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["product_id"], name="costings_co_product_0e58f5_idx"),
                    models.Index(fields=["-calculated_at"], name="costings_co_calcula_f41f6b_idx"),
                ],
            },
        ),
    ]
