# Generated by Django 5.0.14 on 2025-12-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("costings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Update by Admin"),
                    ("auto_fetched", "Auto-fetched from API"),
                    ("manual_refresh", "Manual Refresh from API"),
                    ("fallback", "Fallback Default Rate"),
                    ("api", "External API"),
                    ("bank", "Bank Source"),
                ],
                default="manual",
                help_text="Sumber data nilai tukar",
                max_length=100,
                verbose_name="Rate source",
            ),
        ),
    ]
