# Generated by Django 5.0.14 on 2025-12-06 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyerRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product_category",
                    models.CharField(
                        help_text="Product category (e.g., 'Furniture', 'Textiles')",
                        max_length=255,
                        verbose_name="product category",
                    ),
                ),
                (
                    "hs_code_target",
                    models.CharField(
                        blank=True,
                        help_text="Target HS Code (8-16 digits)",
                        max_length=16,
                        null=True,
                        verbose_name="HS code target",
                    ),
                ),
                (
                    "spec_requirements",
                    models.TextField(help_text="Detailed specification requirements", verbose_name="spec requirements"),
                ),
                (
                    "target_volume",
                    models.PositiveIntegerField(
                        help_text="Target volume/quantity needed", verbose_name="target volume"
                    ),
                ),
                (
                    "destination_country",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 country code (e.g., 'US', 'JP')",
                        max_length=2,
                        verbose_name="destination country",
                    ),
                ),
                (
                    "keyword_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Array of keyword tags for matching",
                        verbose_name="keyword tags",
                    ),
                ),
                (
                    "min_rank_required",
                    models.IntegerField(
                        default=0,
                        help_text="Minimum rank required for UMKM to see this request",
                        verbose_name="min rank required",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Matched", "Matched"), ("Closed", "Closed")],
                        default="Open",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "buyer_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="buyer user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyer Request",
                "verbose_name_plural": "Buyer Requests",
                "db_table": "buyer_requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["buyer_user"], name="buyer_reque_buyer_u_5d548c_idx"),
                    models.Index(fields=["status"], name="buyer_reque_status_7c4f7f_idx"),
                    models.Index(fields=["product_category"], name="buyer_reque_product_313108_idx"),
                    models.Index(fields=["destination_country"], name="buyer_reque_destina_c163be_idx"),
                ],
            },
        ),
    ]
