# Generated by Django 5.0.14 on 2025-12-06 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_requests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuyerProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("company_name", models.CharField(max_length=255, verbose_name="company name")),
                (
                    "contact_info",
                    models.JSONField(
                        default=dict,
                        help_text="Contact information (phone, email, address, website, etc.)",
                        verbose_name="contact info",
                    ),
                ),
                (
                    "preferred_product_categories",
                    models.JSONField(
                        default=list,
                        help_text="Array of product categories buyer typically imports (e.g., ['Makanan Olahan', 'Kerajinan'])",
                        verbose_name="preferred product categories",
                    ),
                ),
                (
                    "source_countries",
                    models.JSONField(
                        default=list,
                        help_text="Array of source country codes (e.g., ['ID'] for Indonesia)",
                        verbose_name="source countries",
                    ),
                ),
                (
                    "business_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Type of business (e.g., 'Importir', 'Distributor', 'Retailer')",
                        max_length=100,
                        verbose_name="business type",
                    ),
                ),
                (
                    "annual_import_volume",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Annual import volume description (e.g., '1000-5000 containers', '50000-100000 units')",
                        max_length=100,
                        verbose_name="annual import volume",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "Buyer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyer Profile",
                "verbose_name_plural": "Buyer Profiles",
                "db_table": "buyer_profiles",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company_name"], name="buyer_profi_company_ec3811_idx")],
            },
        ),
    ]
