# Generated by Django 5.0.14 on 2025-12-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer_requests", "0002_buyerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyerprofile",
            name="annual_import_volume_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed information about import capacity, volume trends, and growth projections",
                verbose_name="annual import volume description",
            ),
        ),
        migrations.AddField(
            model_name="buyerprofile",
            name="business_type_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed description of business operations, distribution channels, and market reach",
                verbose_name="business type description",
            ),
        ),
        migrations.AddField(
            model_name="buyerprofile",
            name="company_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed description of the company, its business activities, and market focus",
                verbose_name="company description",
            ),
        ),
        migrations.AddField(
            model_name="buyerprofile",
            name="preferred_product_categories_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detailed description of preferred product categories, quality requirements, and specific product interests",
                verbose_name="preferred product categories description",
            ),
        ),
        migrations.AddField(
            model_name="buyerprofile",
            name="source_countries_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Description of sourcing strategy, preferred countries, and import experience from these regions",
                verbose_name="source countries description",
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="annual_import_volume",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Annual import volume description (e.g., '1000-5000 containers', '50000-100000 units', '100-500 tons')",
                max_length=100,
                verbose_name="annual import volume",
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="business_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Type of business (e.g., 'Importir', 'Distributor', 'Retailer', 'Trading Company')",
                max_length=100,
                verbose_name="business type",
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="company_name",
            field=models.CharField(
                help_text="Name of the buyer's company or organization", max_length=255, verbose_name="company name"
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="preferred_product_categories",
            field=models.JSONField(
                default=list,
                help_text="Array of product categories buyer typically imports (e.g., ['Makanan Olahan', 'Kerajinan', 'Tekstil']). Categories the buyer is interested in sourcing.",
                verbose_name="preferred product categories",
            ),
        ),
        migrations.AlterField(
            model_name="buyerprofile",
            name="source_countries",
            field=models.JSONField(
                default=list,
                help_text="Array of source country codes where buyer typically imports from (e.g., ['ID'] for Indonesia, ['ID', 'VN'] for multiple countries)",
                verbose_name="source countries",
            ),
        ),
    ]
