# Generated by Django 5.0.14 on 2025-12-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_requests', '0003_buyerprofile_annual_import_volume_description_and_more'),
        ('catalogs', '0008_remove_catalogpricingresult_catalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerrequest',
            name='selected_catalog',
            field=models.ForeignKey(blank=True, help_text='Catalog selected by buyer when closing the request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_requests_selected', to='catalogs.productcatalog', verbose_name='selected catalog'),
        ),
    ]
