# Generated by Django 5.0.14 on 2025-12-05 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('address', models.TextField(verbose_name='address')),
                ('production_capacity_per_month', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='production capacity per month')),
                ('certifications', models.JSONField(blank=True, default=list, help_text='Array of certifications: Halal, ISO, HACCP, SVLK', verbose_name='certifications')),
                ('year_established', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='year established')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'business profile',
                'verbose_name_plural': 'business profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
